sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_stuart_method:
                    name: 'shipping_method'
                    options:
                        custom:
                            stuart_delivery:
                                code: 'stuart_delivery'
                                name: 'Stuart Delivery'
                                calculator:
                                    type: !php/const MonsieurBiz\SyliusStuartDeliveryPlugin\Calculator\StuartCalculator::TYPE
                                    configuration: []
                                enabled: true
                                channels:
                                    - 'FASHION_WEB'
                                zone: 'WORLD'
                monsieurbiz_stuart_delivery:
                    options:
                        shipping_method_rule:
                            -   rule: !php/const MonsieurBiz\SyliusStuartDeliveryPlugin\Checker\Rule\StuartRuleChecker::TYPE
                                configuration: []
                                shipping_methods:
                                    - 'stuart_delivery'
                monsieurbiz_stuart_slot_config:
                    name: 'monsieurbiz_shipping_slot_config'
                    options:
                        custom:
                            stuart_delivery:
                                name: 'Stuart delivery slots'
                                timezone: 'Europe/Paris'
                                rrules:
                                    - 'RRULE:FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=19;BYMINUTE=0;BYSECOND=0'
                                    - 'RRULE:FREQ=HOURLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=7,8,9,10,11,12,13,14,15,16,17,18;BYMINUTE=0,30;BYSECOND=0'
                                preparationDelay: 60
                                pickupDelay: 30
                                durationRange: 60
                                availableSpots: 10
                                color: '#22B99A'
                                shipping_methods:
                                    - 'stuart_delivery'
